#!/usr/bin/env python3
"""
amnezia-dns-bridge: D-Bus shim providing org.freedesktop.resolve1 on Void Linux / non-systemd systems.
Translates AmneziaVPN SetLinkDNS calls directly into openresolv updates.
Includes kernel interface watchdog and exclusive DNS routing to prevent DNS leaks.
Supports AmneziaWG (awg), OpenVPN (tun), WireGuard (wg), and other tunnel interfaces.
"""
import os
import signal
import socket
import subprocess
import sys
import dbus
import dbus.mainloop.glib
import dbus.service
from gi.repository import GLib

RESOLVE_SERVICE = "org.freedesktop.resolve1"
RESOLVE_PATH = "/org/freedesktop/resolve1"
RESOLVE_MANAGER_IFACE = "org.freedesktop.resolve1.Manager"

TUNNEL_PREFIXES = ("tun", "amn", "awg", "wg", "tap", "ppp")


class ResolveManager(dbus.service.Object):
    def __init__(self, bus_name):
        super().__init__(bus_name, RESOLVE_PATH)
        self.link_dns = {}
        self.link_domains = {}

    @dbus.service.method(RESOLVE_MANAGER_IFACE, in_signature='ia(iay)', out_signature='')
    def SetLinkDNS(self, ifindex, resolvers):
        print(f"[DNS Bridge] SetLinkDNS для интерфейса {ifindex}")
        ips = []
        for family, raw_addr in resolvers:
            try:
                addr_bytes = bytes(raw_addr)
                if family == socket.AF_INET and len(addr_bytes) == 4:
                    ip_str = socket.inet_ntop(socket.AF_INET, addr_bytes)
                    ips.append(ip_str)
                elif family == socket.AF_INET6 and len(addr_bytes) == 16:
                    ip_str = socket.inet_ntop(socket.AF_INET6, addr_bytes)
                    ips.append(ip_str)
            except Exception as e:
                print(f"[DNS Bridge] Ошибка разбора IP: {e}")

        if ips:
            print(f"[DNS Bridge] Установка DNS серверов для #{ifindex}: {ips}")
            self.link_dns[int(ifindex)] = ips
            self.apply_dns()

    @dbus.service.method(RESOLVE_MANAGER_IFACE, in_signature='ia(sb)', out_signature='')
    def SetLinkDomains(self, ifindex, domains):
        self.link_domains[int(ifindex)] = [(str(d), bool(s)) for d, s in domains]

    @dbus.service.method(RESOLVE_MANAGER_IFACE, in_signature='ib', out_signature='')
    def SetLinkDefaultRoute(self, ifindex, enable):
        pass

    @dbus.service.method(RESOLVE_MANAGER_IFACE, in_signature='i', out_signature='')
    def RevertLink(self, ifindex):
        ifindex = int(ifindex)
        print(f"[DNS Bridge] RevertLink для интерфейса {ifindex}")
        if ifindex in self.link_dns:
            del self.link_dns[ifindex]
        if ifindex in self.link_domains:
            del self.link_domains[ifindex]
        self.apply_dns()

    @dbus.service.method(dbus.PROPERTIES_IFACE, in_signature='ss', out_signature='v')
    def Get(self, interface_name, property_name):
        if property_name == "Domains":
            domains_list = []
            for ifidx, dlist in self.link_domains.items():
                for dom, search_domain in dlist:
                    domains_list.append((dbus.Int32(ifidx), dbus.String(dom), dbus.Boolean(search_domain)))
            return dbus.Array(domains_list, signature='(isb)')
        return ""

    def apply_dns(self):
        vpn_ips = []
        other_ips = []
        for ifidx, ips in self.link_dns.items():
            ifname = ""
            try:
                ifname = socket.if_indextoname(ifidx)
            except OSError:
                pass

            is_tunnel = any(ifname.startswith(pfx) for pfx in TUNNEL_PREFIXES)
            for ip in ips:
                if is_tunnel:
                    if ip not in vpn_ips:
                        vpn_ips.append(ip)
                else:
                    if ip not in other_ips:
                        other_ips.append(ip)

        # Туннельные VPN DNS идут первыми для предотвращения DNS Leak
        all_ips = vpn_ips + [ip for ip in other_ips if ip not in vpn_ips]

        if all_ips:
            resolv_data = "# Generated by amnezia-dns-bridge\n" + "".join([f"nameserver {ip}\n" for ip in all_ips])
            try:
                proc = subprocess.run(
                    ["resolvconf", "-a", "amnezia-vpn", "-x", "-m", "0"],
                    input=resolv_data.encode(),
                    capture_output=True,
                    check=False,
                )
                if proc.returncode == 0:
                    print(f"[DNS Bridge] DNS успешно применен через resolvconf: {all_ips}")
                else:
                    print(f"[DNS Bridge] Предупреждение resolvconf (код {proc.returncode}): {proc.stderr.decode().strip()}")
            except FileNotFoundError:
                print("[DNS Bridge] Утилита resolvconf не найдена! Установите пакет openresolv.")
        else:
            try:
                subprocess.run(["resolvconf", "-d", "amnezia-vpn"], capture_output=True, check=False)
                print("[DNS Bridge] Записи DNS для amnezia-vpn удалены из resolvconf.")
            except FileNotFoundError:
                pass

    def cleanup(self):
        self.link_dns.clear()
        self.link_domains.clear()
        self.apply_dns()

    def check_interfaces(self):
        """Watchdog: проверяет, живы ли интерфейсы. Если VPN туннель закрыт, автоматически сбрасывает DNS."""
        if not self.link_dns:
            return True
        changed = False
        for ifidx in list(self.link_dns.keys()):
            try:
                socket.if_indextoname(ifidx)
            except OSError:
                print(f"[DNS Bridge] Интерфейс #{ifidx} удален/закрыт. Автоматический сброс DNS...")
                del self.link_dns[ifidx]
                if ifidx in self.link_domains:
                    del self.link_domains[ifidx]
                changed = True
        if changed:
            self.apply_dns()
        return True


def main():
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
    try:
        bus = dbus.SystemBus()
    except Exception as e:
        print(f"[DNS Bridge] Ошибка подключения к системной шине D-Bus: {e}")
        sys.exit(1)

    try:
        bus_name = dbus.service.BusName(RESOLVE_SERVICE, bus, do_not_queue=True)
    except Exception as e:
        print(f"[DNS Bridge] Не удалось зарегистрировать имя {RESOLVE_SERVICE} на D-Bus: {e}")
        sys.exit(1)

    manager = ResolveManager(bus_name)
    loop = GLib.MainLoop()

    # Запуск периодического watchdog каждые 2 секунды
    GLib.timeout_add_seconds(2, manager.check_interfaces)

    def handle_signal(sig, frame):
        print("\n[DNS Bridge] Получен сигнал остановки, восстановление DNS...")
        manager.cleanup()
        loop.quit()

    signal.signal(signal.SIGTERM, handle_signal)
    signal.signal(signal.SIGINT, handle_signal)
    signal.signal(signal.SIGHUP, handle_signal)

    print("[DNS Bridge] D-Bus DNS-мост успешно запущен и ожидает запросов.")
    try:
        loop.run()
    except (KeyboardInterrupt, SystemExit):
        manager.cleanup()


if __name__ == "__main__":
    main()
